name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag for the generated files (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Needed for creating releases

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests python-dotenv
        
    - name: Create output directories
      run: |
        mkdir -p layers
        mkdir -p styles
        mkdir -p dist
        
    - name: Set up environment variables
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        LAYERDIR: ./layers
        STYLEDIR: ./styles
      run: |
        echo "BITBUCKET_USERNAME=$BITBUCKET_USERNAME" >> .env
        echo "BITBUCKET_TOKEN=$BITBUCKET_TOKEN" >> .env
        echo "LAYERDIR=$LAYERDIR" >> .env
        echo "STYLEDIR=$STYLEDIR" >> .env
        
    - name: Run Python scripts
      run: |
        python create_forecast_layers.py
        python create_forecast_styles.py
        
    - name: Prepare release files
      run: |
        # Create release directory
        mkdir -p dist/release
        cp layers/*.json dist/release/
        cp styles/*.json dist/release/
        
        # Add metadata
        echo "${{ github.event.inputs.version_tag }}" > dist/release/version.txt
        echo "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > dist/release/generated_at.txt
        
        # Create README
        cat > dist/release/README.md << EOF
        # CAMS webcharts definitions
        
        Version: ${{ github.event.inputs.version_tag }}
        Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        
        Automatically generated with https://github.com/${{ github.repository }}
        
        This release contains JSON definition files for the CAMS ecCharts web products.
        EOF
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Delete tag both locally and remotely if it exists
        if git rev-parse "${{ github.event.inputs.version_tag }}" >/dev/null 2>&1; then
          echo "Tag exists, deleting..."
          git tag -d ${{ github.event.inputs.version_tag }} || true
          git push --delete origin ${{ github.event.inputs.version_tag }} || true
        fi
        
        # Delete release if it exists
        if gh release view "${{ github.event.inputs.version_tag }}" >/dev/null 2>&1; then
          echo "Release exists, deleting..."
          gh release delete ${{ github.event.inputs.version_tag }} --yes || true
        fi
        
        # Create fresh tag and release
        git tag ${{ github.event.inputs.version_tag }}
        git push origin ${{ github.event.inputs.version_tag }}
        
        # Create GitHub release with all files
        cd dist/release
        gh release create ${{ github.event.inputs.version_tag }} \
          --title "webchart-definitions-${{ github.event.inputs.version_tag }}" \
          --notes-file README.md \
          *