name: Generate JSON Files

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag for the generated files (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Needed for creating releases

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests python-dotenv
        
    - name: Create output directories
      run: |
        mkdir -p layers
        mkdir -p styles
        mkdir -p dist
        
    - name: Set up environment variables
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        LAYERDIR: ./layers
        STYLEDIR: ./styles
      run: |
        echo "BITBUCKET_USERNAME=$BITBUCKET_USERNAME" >> .env
        echo "BITBUCKET_TOKEN=$BITBUCKET_TOKEN" >> .env
        echo "LAYERDIR=$LAYERDIR" >> .env
        echo "STYLEDIR=$STYLEDIR" >> .env
        
    - name: Run Python scripts
      run: |
        python create_forecast_layers.py
        python create_forecast_styles.py
        
    - name: Prepare release files
      run: |
        # Create release directory
        mkdir -p dist/release
        cp layers/*.json dist/release/
        cp styles/*.json dist/release/
        
        # Add metadata
        echo "${{ github.event.inputs.version_tag }}" > dist/release/version.txt
        echo "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > dist/release/generated_at.txt
        
        # Create README
        cat > dist/release/README.md << EOF
        # CAMS WebCharts Definitions
        
        Version: ${{ github.event.inputs.version_tag }}
        Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        
        Automatically generated with https://github.com/${{ github.repository }}
        
        This release contains JSON definition files for the CAMS ecCharts web products.
        EOF
        
        # Create zip archive
        cd dist/release
        zip -r ../cams-webcharts-definitions-${{ github.event.inputs.version_tag }}.zip *
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create git tag
        git tag ${{ github.event.inputs.version_tag }}
        git push origin ${{ github.event.inputs.version_tag }}
        
        # Create GitHub release
        gh release create ${{ github.event.inputs.version_tag }} \
          --title "CAMS WebCharts Definitions ${{ github.event.inputs.version_tag }}" \
          --notes-file dist/release/README.md \
          dist/cams-webcharts-definitions-${{ github.event.inputs.version_tag }}.zip
        
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: json-files-${{ github.event.inputs.version_tag }}
        path: dist/release
        retention-days: 90 