name: Generate JSON Files

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests python-dotenv
        
    - name: Create output directories
      run: |
        mkdir -p layers
        mkdir -p styles
        
    - name: Set up environment variables
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        LAYERDIR: ./layers
        STYLEDIR: ./styles
      run: |
        echo "BITBUCKET_USERNAME=$BITBUCKET_USERNAME" >> .env
        echo "BITBUCKET_TOKEN=$BITBUCKET_TOKEN" >> .env
        echo "LAYERDIR=$LAYERDIR" >> .env
        echo "STYLEDIR=$STYLEDIR" >> .env
        
    - name: Run Python scripts
      run: |
        python create_forecast_layers.py
        python create_forecast_styles.py
        
    - name: Upload layer files
      uses: actions/upload-artifact@v3
      with:
        name: layer-files
        path: layers/*.json
        
    - name: Upload style files
      uses: actions/upload-artifact@v3
      with:
        name: style-files
        path: styles/*.json 